export const defaultValues = {
	URL: '',
	code: '',
	titleTest: '',
	consoleErrorsTest: '',
	manualTests: '',
	sourceCode: '',
	toolCICD: '',
	browserType: '',
	browsersHub: '',
	notification: '',
	testManagement: '',
	testsResults: '',
	attachments: '',
}
